// AUTO-GENERATED by generate-bank.js (v3) — DO NOT EDIT BY HAND.
// Every computational answer verified against complex/ω-arithmetic at build time.
// Option positions are deterministically shuffled (no answer-index bias).
// Question count: 80
const BANK = [
 {
  "id": "b70",
  "trap": "G",
  "difficulty": 2,
  "prompt": "The sum of all 7th roots of unity is:",
  "options": [
   "7",
   "1",
   "0",
   "-1"
  ],
  "answer": 2,
  "script": [
   "The 7 roots are symmetric about the origin.",
   "Their sum (and 1+x+…+xⁿ⁻¹) is 0."
  ],
  "mistake": "Forgetting all nth roots (n>1) always cancel to zero.",
  "why": "Symmetric points around the circle sum to 0 — generalizes 1+ω+ω²=0."
 },
 {
  "id": "b61",
  "trap": "H",
  "difficulty": 3,
  "prompt": "Value of (1 + 1ω + 2ω²)(1 + 1ω² + 2ω) ?",
  "options": [
   "7",
   "1",
   "3",
   "0"
  ],
  "answer": 1,
  "script": [
   "This product is the identity a²+b²+c²−ab−bc−ca.",
   "= 1²+1²+2² − (1·1+1·2+2·1) = 1."
  ],
  "mistake": "Multiplying out all nine ω-terms by hand.",
  "why": "Recognize the conjugate-pair identity — it collapses to a simple real number."
 },
 {
  "id": "b64",
  "trap": "H",
  "difficulty": 3,
  "prompt": "x² + x + 1 divides x^(2n) + xⁿ + 1 for:",
  "options": [
   "all positive integers n",
   "all positive integers n not divisible by 3",
   "only even n",
   "only n divisible by 3"
  ],
  "answer": 1,
  "script": [
   "x²+x+1 | P(x) iff P(ω)=0. Here P(ω)=ω^(2n)+ωⁿ+1.",
   "That is 0 unless 3|n (then it equals 3). So it divides iff 3∤n."
  ],
  "mistake": "Answering 'all n' — it fails exactly when n is a multiple of 3.",
  "why": "The divisibility flips on n mod 3 — the value is 0 (divides) or 3 (does not)."
 },
 {
  "id": "b29",
  "trap": "D",
  "difficulty": 2,
  "prompt": "Value of 1/(1+ω) + 1/(1+ω²) ?",
  "options": [
   "0",
   "-1",
   "1",
   "ω"
  ],
  "answer": 2,
  "script": [
   "1/(1+ω)=1/(−ω²)=−ω,  1/(1+ω²)=1/(−ω)=−ω².",
   "Sum = −(ω+ω²) = −(−1) = 1."
  ],
  "mistake": "Cross-multiplying and dropping a sign.",
  "why": "Small fractions bait rushing; every step is a rewrite."
 },
 {
  "id": "b14",
  "trap": "C",
  "difficulty": 3,
  "prompt": "Remainder when x^200 + x^100 + 1 is divided by x² + x + 1 (give its value at x = ω):",
  "options": [
   "-1",
   "1",
   "ω",
   "0"
  ],
  "answer": 3,
  "script": [
   "Roots of x²+x+1 are ω, ω²; the remainder equals the polynomial at x = ω.",
   "Plug x=ω, reduce powers mod 3 → ω+ω²+1 = 0."
  ],
  "mistake": "Attempting polynomial long division instead of evaluating at the root.",
  "why": "x²+x+1 is a disguise for (x−ω)(x−ω²) — evaluate at ω, never long-divide."
 },
 {
  "id": "b17",
  "trap": "C",
  "difficulty": 3,
  "prompt": "For ω a cube root of unity, the value of ω^6 + ω^3 + 1 is:",
  "options": [
   "3",
   "0",
   "1",
   "ω"
  ],
  "answer": 0,
  "script": [
   "Reduce ω^6=ω^0, ω^3=ω^0.",
   "Both become 1 → 1+1+1 = 3."
  ],
  "mistake": "Assuming the answer is always 0 — it is 3 exactly when n is a multiple of 3.",
  "why": "Same shape, different answer by n mod 3. The examiner flips 0↔3 to punish autopilot."
 },
 {
  "id": "b60",
  "trap": "H",
  "difficulty": 3,
  "prompt": "Value of (1 + 2ω + 3ω²)(1 + 2ω² + 3ω) ?",
  "options": [
   "1",
   "6",
   "3",
   "0"
  ],
  "answer": 2,
  "script": [
   "This product is the identity a²+b²+c²−ab−bc−ca.",
   "= 1²+2²+3² − (1·2+2·3+3·1) = 3."
  ],
  "mistake": "Multiplying out all nine ω-terms by hand.",
  "why": "Recognize the conjugate-pair identity — it collapses to a simple real number."
 },
 {
  "id": "b2",
  "trap": "A",
  "difficulty": 1,
  "prompt": "If ω is a non-real cube root of unity, then ω^17 = ?",
  "options": [
   "ω²",
   "1",
   "-1",
   "ω"
  ],
  "answer": 0,
  "script": [
   "17 mod 3 = 2.",
   "ω^17 = ω^2 = ω²."
  ],
  "mistake": "Letting the big exponent intimidate you, or reducing mod 2 instead of mod 3.",
  "why": "Pure exponent disguise — the size of the power carries zero weight. Reduce mod 3 on sight."
 },
 {
  "id": "b56",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Using De Moivre, (1+i)⁸ = ?",
  "options": [
   "16i",
   "0",
   "16",
   "-16"
  ],
  "answer": 2,
  "script": [
   "Convert the base to polar r∠θ, then apply (r∠θ)ⁿ = rⁿ∠nθ.",
   "(1+i)⁸ = 16."
  ],
  "mistake": "Expanding the binomial by hand instead of using polar form.",
  "why": "De Moivre turns a brutal expansion into one modulus power and one angle multiply."
 },
 {
  "id": "b66",
  "trap": "H",
  "difficulty": 3,
  "prompt": "The value of C(9,0) + C(9,3) + C(9,6) + … is:",
  "options": [
   "168",
   "170",
   "512",
   "171"
  ],
  "answer": 1,
  "script": [
   "Use the root-of-unity filter: sum of every 3rd binomial = (2ⁿ + 2cos(nπ/3))/3.",
   "= 170."
  ],
  "mistake": "Adding the binomials one by one and slipping.",
  "why": "Cube roots of unity act as a sieve picking every third term — that is the filter trick."
 },
 {
  "id": "b77",
  "trap": "A",
  "difficulty": 1,
  "prompt": "Value of ω^2 · ω^3 ?",
  "options": [
   "-1",
   "ω²",
   "ω",
   "1"
  ],
  "answer": 1,
  "script": [
   "Add exponents: ω^2·ω^3=ω^5.",
   "5 mod 3 = 2 ⇒ ω²."
  ],
  "mistake": "Multiplying instead of adding exponents.",
  "why": "Powers of ω add exponents, then reduce mod 3."
 },
 {
  "id": "b41",
  "trap": "G",
  "difficulty": 1,
  "prompt": "For a non-zero complex number z, how many distinct values does z^(1/12) have?",
  "options": [
   "1",
   "12",
   "11",
   "2"
  ],
  "answer": 1,
  "script": [
   "Every non-zero z has exactly n distinct nth roots.",
   "Here n = 12."
  ],
  "mistake": "Thinking there is one root, or 2 like a square root.",
  "why": "nth roots come in exactly n, equally spaced 2π/12 apart."
 },
 {
  "id": "b16",
  "trap": "C",
  "difficulty": 3,
  "prompt": "Remainder when x^20 + x^10 + 1 is divided by x² + x + 1 (give its value at x = ω):",
  "options": [
   "1",
   "0",
   "ω",
   "-1"
  ],
  "answer": 1,
  "script": [
   "Roots of x²+x+1 are ω, ω²; the remainder equals the polynomial at x = ω.",
   "Plug x=ω, reduce powers mod 3 → ω+ω²+1 = 0."
  ],
  "mistake": "Attempting polynomial long division instead of evaluating at the root.",
  "why": "x²+x+1 is a disguise for (x−ω)(x−ω²) — evaluate at ω, never long-divide."
 },
 {
  "id": "b30",
  "trap": "D",
  "difficulty": 2,
  "prompt": "Value of (1 + ω)/(1 + ω²) ?",
  "options": [
   "ω",
   "-1",
   "ω²",
   "-ω"
  ],
  "answer": 0,
  "script": [
   "(−ω²)/(−ω) = ω²/ω = ω."
  ],
  "mistake": "Sign error in either rewrite.",
  "why": "Ratio of the two sign-rewrites cancels to a single ω."
 },
 {
  "id": "b32",
  "trap": "E",
  "difficulty": 1,
  "prompt": "The centroid of the triangle with vertices 1, ω, ω² is:",
  "options": [
   "0 (origin)",
   "1",
   "ω",
   "(1+i)/3"
  ],
  "answer": 0,
  "script": [
   "Centroid = (1+ω+ω²)/3 = 0."
  ],
  "mistake": "Averaging coordinates the long way.",
  "why": "Centroid is the sum identity over 3 = 0."
 },
 {
  "id": "b18",
  "trap": "C",
  "difficulty": 3,
  "prompt": "For ω a cube root of unity, the value of ω^12 + ω^6 + 1 is:",
  "options": [
   "0",
   "ω",
   "3",
   "1"
  ],
  "answer": 2,
  "script": [
   "Reduce ω^12=ω^0, ω^6=ω^0.",
   "Both become 1 → 1+1+1 = 3."
  ],
  "mistake": "Assuming the answer is always 0 — it is 3 exactly when n is a multiple of 3.",
  "why": "Same shape, different answer by n mod 3. The examiner flips 0↔3 to punish autopilot."
 },
 {
  "id": "b76",
  "trap": "A",
  "difficulty": 1,
  "prompt": "Value of ω^4 · ω^4 ?",
  "options": [
   "ω",
   "1",
   "ω²",
   "-1"
  ],
  "answer": 2,
  "script": [
   "Add exponents: ω^4·ω^4=ω^8.",
   "8 mod 3 = 2 ⇒ ω²."
  ],
  "mistake": "Multiplying instead of adding exponents.",
  "why": "Powers of ω add exponents, then reduce mod 3."
 },
 {
  "id": "b12",
  "trap": "B",
  "difficulty": 2,
  "prompt": "Value of ω^50 + ω^100 ?",
  "options": [
   "0",
   "-1",
   "1",
   "ω"
  ],
  "answer": 1,
  "script": [
   "Reduce: ω^50=ω^2, ω^100=ω^1.",
   "Their sum is ω+ω² = −1."
  ],
  "mistake": "Computing huge powers directly instead of reducing first.",
  "why": "Two powers chosen so they reduce to ω + ω² = −1."
 },
 {
  "id": "b79",
  "trap": "H",
  "difficulty": 2,
  "prompt": "Value of 2³ + 3³ + 4³ − 3·2·3·4 ?",
  "options": [
   "0",
   "99",
   "30",
   "27"
  ],
  "answer": 3,
  "script": [
   "Use a³+b³+c³−3abc = (a+b+c)(a²+b²+c²−ab−bc−ca).",
   "= (9)·(3) = 27."
  ],
  "mistake": "Computing each cube separately and slipping arithmetic.",
  "why": "The ω-factorization (a+bω+cω²)(a+bω²+cω) underlies this identity — recognize and factor."
 },
 {
  "id": "b9",
  "trap": "B",
  "difficulty": 1,
  "prompt": "Value of ω^2024 + ω^2025 + ω^2026 ?",
  "options": [
   "0",
   "ω²",
   "1",
   "ω"
  ],
  "answer": 0,
  "script": [
   "Three consecutive powers reduce to 1, ω, ω² in some order.",
   "1 + ω + ω² = 0."
  ],
  "mistake": "Not spotting that consecutive powers form the zero-sum identity.",
  "why": "Consecutive exponents are engineered to land on 1+ω+ω²=0. Recognize, don't compute."
 },
 {
  "id": "b58",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Using De Moivre, (√3+i)⁶ = ?",
  "options": [
   "0",
   "-64",
   "64i",
   "64"
  ],
  "answer": 1,
  "script": [
   "Convert the base to polar r∠θ, then apply (r∠θ)ⁿ = rⁿ∠nθ.",
   "(√3+i)⁶ = -64."
  ],
  "mistake": "Expanding the binomial by hand instead of using polar form.",
  "why": "De Moivre turns a brutal expansion into one modulus power and one angle multiply."
 },
 {
  "id": "b6",
  "trap": "A",
  "difficulty": 2,
  "prompt": "If ω is a non-real cube root of unity, then ω^4000 = ?",
  "options": [
   "ω",
   "-1",
   "1",
   "ω²"
  ],
  "answer": 0,
  "script": [
   "4000 mod 3 = 1.",
   "ω^4000 = ω^1 = ω."
  ],
  "mistake": "Letting the big exponent intimidate you, or reducing mod 2 instead of mod 3.",
  "why": "Pure exponent disguise — the size of the power carries zero weight. Reduce mod 3 on sight."
 },
 {
  "id": "b19",
  "trap": "C",
  "difficulty": 3,
  "prompt": "For ω a cube root of unity, the value of ω^8 + ω^4 + 1 is:",
  "options": [
   "1",
   "3",
   "ω",
   "0"
  ],
  "answer": 3,
  "script": [
   "Reduce ω^8=ω^2, ω^4=ω^1.",
   "Get ω+ω²+1 = 0."
  ],
  "mistake": "Assuming the answer is always 0 — it is 3 exactly when n is a multiple of 3.",
  "why": "Same shape, different answer by n mod 3. The examiner flips 0↔3 to punish autopilot."
 },
 {
  "id": "b31",
  "trap": "E",
  "difficulty": 1,
  "prompt": "1, ω, ω² are vertices of a triangle in the Argand plane. Its area is:",
  "options": [
   "3√3/4",
   "3/4",
   "√3/4",
   "√3"
  ],
  "answer": 0,
  "script": [
   "All on |z|=1, 120° apart ⇒ equilateral, R=1.",
   "Area = (3√3/4)R² = 3√3/4."
  ],
  "mistake": "Using the shoelace formula on coordinates.",
  "why": "Always the unit-circle equilateral triangle — read it off."
 },
 {
  "id": "b53",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Which of these is a cube root of −8?",
  "options": [
   "2i",
   "1+i√3",
   "√3+i",
   "−1−i√3"
  ],
  "answer": 1,
  "script": [
   "Convert −8 to polar; its 3 roots have modulus |−8|^(1/3) at equally spaced arguments.",
   "Only 1+i√3 matches both modulus and an allowed argument: (1+i√3)^3 = −8."
  ],
  "mistake": "Picking a number with the right modulus but the wrong argument.",
  "why": "Polar-first: a true root must match BOTH the modulus and one of the n allowed angles."
 },
 {
  "id": "b38",
  "trap": "F",
  "difficulty": 3,
  "prompt": "The determinant |1 1 1 ; 1 ω ω² ; 1 ω² ω| equals:",
  "options": [
   "0",
   "-3√3 i",
   "3",
   "3√3 i"
  ],
  "answer": 1,
  "script": [
   "Subtract row1 from rows 2,3 → zeros in column 1, then expand the 2×2.",
   "Result = (ω−1)(ω²−1)(ω²−ω) = 3·(−√3 i) = −3√3 i."
  ],
  "mistake": "Cofactor-expanding the full 3×3 without first creating zeros.",
  "why": "A Vandermonde-style ω determinant — its value is purely imaginary, −3√3 i."
 },
 {
  "id": "b5",
  "trap": "A",
  "difficulty": 2,
  "prompt": "If ω is a non-real cube root of unity, then ω^2024 = ?",
  "options": [
   "ω²",
   "1",
   "-1",
   "ω"
  ],
  "answer": 0,
  "script": [
   "2024 mod 3 = 2.",
   "ω^2024 = ω^2 = ω²."
  ],
  "mistake": "Letting the big exponent intimidate you, or reducing mod 2 instead of mod 3.",
  "why": "Pure exponent disguise — the size of the power carries zero weight. Reduce mod 3 on sight."
 },
 {
  "id": "b62",
  "trap": "H",
  "difficulty": 3,
  "prompt": "Value of (1 + 2ω + 3ω²)/(3 + ω + 2ω²) ?",
  "options": [
   "ω",
   "ω²",
   "1",
   "-1"
  ],
  "answer": 1,
  "script": [
   "Denominator = ω·(numerator), since multiplying a+bω+cω² by ω cycles the coefficients.",
   "Ratio = 1/ω = ω²."
  ],
  "mistake": "Rationalising the denominator the long way.",
  "why": "Cyclic coefficient shift means the ratio is just a power of ω."
 },
 {
  "id": "b54",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Which of these is a cube root of 8?",
  "options": [
   "1−i",
   "1+i√3",
   "−1+i√3",
   "2i"
  ],
  "answer": 2,
  "script": [
   "Convert 8 to polar; its 3 roots have modulus |8|^(1/3) at equally spaced arguments.",
   "Only −1+i√3 matches both modulus and an allowed argument: (−1+i√3)^3 = 8."
  ],
  "mistake": "Picking a number with the right modulus but the wrong argument.",
  "why": "Polar-first: a true root must match BOTH the modulus and one of the n allowed angles."
 },
 {
  "id": "b78",
  "trap": "H",
  "difficulty": 2,
  "prompt": "Value of 1³ + 2³ + 3³ − 3·1·2·3 ?",
  "options": [
   "36",
   "18",
   "0",
   "21"
  ],
  "answer": 1,
  "script": [
   "Use a³+b³+c³−3abc = (a+b+c)(a²+b²+c²−ab−bc−ca).",
   "= (6)·(3) = 18."
  ],
  "mistake": "Computing each cube separately and slipping arithmetic.",
  "why": "The ω-factorization (a+bω+cω²)(a+bω²+cω) underlies this identity — recognize and factor."
 },
 {
  "id": "b15",
  "trap": "C",
  "difficulty": 3,
  "prompt": "Remainder when x^8 + x^4 + 1 is divided by x² + x + 1 (give its value at x = ω):",
  "options": [
   "0",
   "1",
   "-1",
   "ω"
  ],
  "answer": 0,
  "script": [
   "Roots of x²+x+1 are ω, ω²; the remainder equals the polynomial at x = ω.",
   "Plug x=ω, reduce powers mod 3 → ω+ω²+1 = 0."
  ],
  "mistake": "Attempting polynomial long division instead of evaluating at the root.",
  "why": "x²+x+1 is a disguise for (x−ω)(x−ω²) — evaluate at ω, never long-divide."
 },
 {
  "id": "b40",
  "trap": "G",
  "difficulty": 1,
  "prompt": "For a non-zero complex number z, how many distinct values does z^(1/7) have?",
  "options": [
   "7",
   "1",
   "2",
   "6"
  ],
  "answer": 0,
  "script": [
   "Every non-zero z has exactly n distinct nth roots.",
   "Here n = 7."
  ],
  "mistake": "Thinking there is one root, or 2 like a square root.",
  "why": "nth roots come in exactly n, equally spaced 2π/7 apart."
 },
 {
  "id": "b8",
  "trap": "B",
  "difficulty": 1,
  "prompt": "Value of ω^99 + ω^100 + ω^101 ?",
  "options": [
   "ω²",
   "0",
   "1",
   "ω"
  ],
  "answer": 1,
  "script": [
   "Three consecutive powers reduce to 1, ω, ω² in some order.",
   "1 + ω + ω² = 0."
  ],
  "mistake": "Not spotting that consecutive powers form the zero-sum identity.",
  "why": "Consecutive exponents are engineered to land on 1+ω+ω²=0. Recognize, don't compute."
 },
 {
  "id": "b73",
  "trap": "G",
  "difficulty": 2,
  "prompt": "The product of all 4th roots of unity is:",
  "options": [
   "0",
   "-1",
   "1",
   "4"
  ],
  "answer": 1,
  "script": [
   "Product of nth roots of unity = (−1)^(n+1).",
   "For n=4 this is -1."
  ],
  "mistake": "Assuming the product is always 1.",
  "why": "Sign alternates with n: odd n → 1, even n → −1."
 },
 {
  "id": "b42",
  "trap": "G",
  "difficulty": 2,
  "prompt": "Each of the cube roots of 8i has modulus:",
  "options": [
   "4",
   "3",
   "2",
   "1"
  ],
  "answer": 2,
  "script": [
   "Modulus of every nth root = |w|^(1/n).",
   "|8i|^(1/3) = 2."
  ],
  "mistake": "Taking the modulus of the number itself, not its nth root.",
  "why": "All nth roots lie on one circle of radius |w|^(1/n) = 2."
 },
 {
  "id": "b11",
  "trap": "B",
  "difficulty": 2,
  "prompt": "Value of ω^10 + ω^20 ?",
  "options": [
   "ω",
   "0",
   "-1",
   "1"
  ],
  "answer": 2,
  "script": [
   "Reduce: ω^10=ω^1, ω^20=ω^2.",
   "Their sum is ω+ω² = −1."
  ],
  "mistake": "Computing huge powers directly instead of reducing first.",
  "why": "Two powers chosen so they reduce to ω + ω² = −1."
 },
 {
  "id": "b7",
  "trap": "B",
  "difficulty": 1,
  "prompt": "Value of ω^0 + ω^1 + ω^2 ?",
  "options": [
   "0",
   "ω",
   "ω²",
   "1"
  ],
  "answer": 0,
  "script": [
   "Three consecutive powers reduce to 1, ω, ω² in some order.",
   "1 + ω + ω² = 0."
  ],
  "mistake": "Not spotting that consecutive powers form the zero-sum identity.",
  "why": "Consecutive exponents are engineered to land on 1+ω+ω²=0. Recognize, don't compute."
 },
 {
  "id": "b75",
  "trap": "A",
  "difficulty": 1,
  "prompt": "Value of ω^5 · ω^7 ?",
  "options": [
   "ω",
   "ω²",
   "1",
   "-1"
  ],
  "answer": 2,
  "script": [
   "Add exponents: ω^5·ω^7=ω^12.",
   "12 mod 3 = 0 ⇒ 1."
  ],
  "mistake": "Multiplying instead of adding exponents.",
  "why": "Powers of ω add exponents, then reduce mod 3."
 },
 {
  "id": "b69",
  "trap": "G",
  "difficulty": 2,
  "prompt": "The sum of all 5th roots of unity is:",
  "options": [
   "0",
   "-1",
   "1",
   "5"
  ],
  "answer": 0,
  "script": [
   "The 5 roots are symmetric about the origin.",
   "Their sum (and 1+x+…+xⁿ⁻¹) is 0."
  ],
  "mistake": "Forgetting all nth roots (n>1) always cancel to zero.",
  "why": "Symmetric points around the circle sum to 0 — generalizes 1+ω+ω²=0."
 },
 {
  "id": "b57",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Using De Moivre, (1+i)⁴ = ?",
  "options": [
   "0",
   "4",
   "-4",
   "16i"
  ],
  "answer": 2,
  "script": [
   "Convert the base to polar r∠θ, then apply (r∠θ)ⁿ = rⁿ∠nθ.",
   "(1+i)⁴ = -4."
  ],
  "mistake": "Expanding the binomial by hand instead of using polar form.",
  "why": "De Moivre turns a brutal expansion into one modulus power and one angle multiply."
 },
 {
  "id": "b68",
  "trap": "H",
  "difficulty": 2,
  "prompt": "Value of (1+ω)(1+ω²)(1+ω⁴)(1+ω⁸) ?",
  "options": [
   "1",
   "0",
   "ω²",
   "-1"
  ],
  "answer": 0,
  "script": [
   "ω⁴=ω, ω⁸=ω² ⇒ [(1+ω)(1+ω²)]² .",
   "(1+ω)(1+ω²)=1 ⇒ answer 1."
  ],
  "mistake": "Multiplying all four factors blindly.",
  "why": "Reduce exponents first, then the product squares to 1."
 },
 {
  "id": "b22",
  "trap": "C",
  "difficulty": 2,
  "prompt": "Value of ω^6 − 1 ?",
  "options": [
   "1",
   "-1",
   "0",
   "ω"
  ],
  "answer": 2,
  "script": [
   "6 is a multiple of 3 ⇒ ω^6 = 1.",
   "1 − 1 = 0."
  ],
  "mistake": "Forgetting ω^(3k)=1.",
  "why": "Multiples of 3 collapse the power to 1."
 },
 {
  "id": "b44",
  "trap": "G",
  "difficulty": 2,
  "prompt": "Each of the cube roots of 27 has modulus:",
  "options": [
   "6",
   "4",
   "3",
   "1"
  ],
  "answer": 2,
  "script": [
   "Modulus of every nth root = |w|^(1/n).",
   "|27|^(1/3) = 3."
  ],
  "mistake": "Taking the modulus of the number itself, not its nth root.",
  "why": "All nth roots lie on one circle of radius |w|^(1/n) = 3."
 },
 {
  "id": "b59",
  "trap": "H",
  "difficulty": 3,
  "prompt": "Value of (2 + 3ω + 4ω²)(2 + 3ω² + 4ω) ?",
  "options": [
   "0",
   "1",
   "6",
   "3"
  ],
  "answer": 3,
  "script": [
   "This product is the identity a²+b²+c²−ab−bc−ca.",
   "= 2²+3²+4² − (2·3+3·4+4·2) = 3."
  ],
  "mistake": "Multiplying out all nine ω-terms by hand.",
  "why": "Recognize the conjugate-pair identity — it collapses to a simple real number."
 },
 {
  "id": "b65",
  "trap": "H",
  "difficulty": 3,
  "prompt": "The value of C(6,0) + C(6,3) + C(6,6) + … is:",
  "options": [
   "22",
   "64",
   "21",
   "20"
  ],
  "answer": 0,
  "script": [
   "Use the root-of-unity filter: sum of every 3rd binomial = (2ⁿ + 2cos(nπ/3))/3.",
   "= 22."
  ],
  "mistake": "Adding the binomials one by one and slipping.",
  "why": "Cube roots of unity act as a sieve picking every third term — that is the filter trick."
 },
 {
  "id": "b1",
  "trap": "A",
  "difficulty": 1,
  "prompt": "If ω is a non-real cube root of unity, then ω^8 = ?",
  "options": [
   "-1",
   "ω",
   "ω²",
   "1"
  ],
  "answer": 2,
  "script": [
   "8 mod 3 = 2.",
   "ω^8 = ω^2 = ω²."
  ],
  "mistake": "Letting the big exponent intimidate you, or reducing mod 2 instead of mod 3.",
  "why": "Pure exponent disguise — the size of the power carries zero weight. Reduce mod 3 on sight."
 },
 {
  "id": "b33",
  "trap": "E",
  "difficulty": 2,
  "prompt": "The circumradius of the triangle formed by 1, ω, ω² is:",
  "options": [
   "1/2",
   "√3",
   "1",
   "3/4"
  ],
  "answer": 2,
  "script": [
   "All three lie on |z|=1 ⇒ circumradius = 1."
  ],
  "mistake": "Computing side then R=a/√3 and slipping.",
  "why": "They sit ON the unit circle — R=1."
 },
 {
  "id": "b52",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Which of these is a cube root of 8i?",
  "options": [
   "√3+i",
   "1+i√3",
   "2+i",
   "√3−i"
  ],
  "answer": 0,
  "script": [
   "Convert 8i to polar; its 3 roots have modulus |8i|^(1/3) at equally spaced arguments.",
   "Only √3+i matches both modulus and an allowed argument: (√3+i)^3 = 8i."
  ],
  "mistake": "Picking a number with the right modulus but the wrong argument.",
  "why": "Polar-first: a true root must match BOTH the modulus and one of the n allowed angles."
 },
 {
  "id": "b25",
  "trap": "D",
  "difficulty": 2,
  "prompt": "Value of (1 + ω)^7 ?",
  "options": [
   "ω",
   "1",
   "-ω",
   "ω²",
   "-ω²",
   "-1"
  ],
  "answer": 4,
  "script": [
   "1 + ω = −ω².",
   "(−ω²)^7 = (−1)^7·ω^2."
  ],
  "mistake": "Expanding the binomial instead of rewriting 1+ω = −ω².",
  "why": "Sign-bait: rewrite the base first, then the power is a one-liner."
 },
 {
  "id": "b71",
  "trap": "G",
  "difficulty": 2,
  "prompt": "The sum of all 8th roots of unity is:",
  "options": [
   "1",
   "8",
   "0",
   "-1"
  ],
  "answer": 2,
  "script": [
   "The 8 roots are symmetric about the origin.",
   "Their sum (and 1+x+…+xⁿ⁻¹) is 0."
  ],
  "mistake": "Forgetting all nth roots (n>1) always cancel to zero.",
  "why": "Symmetric points around the circle sum to 0 — generalizes 1+ω+ω²=0."
 },
 {
  "id": "b4",
  "trap": "A",
  "difficulty": 2,
  "prompt": "If ω is a non-real cube root of unity, then ω^100 = ?",
  "options": [
   "ω",
   "ω²",
   "1",
   "-1"
  ],
  "answer": 0,
  "script": [
   "100 mod 3 = 1.",
   "ω^100 = ω^1 = ω."
  ],
  "mistake": "Letting the big exponent intimidate you, or reducing mod 2 instead of mod 3.",
  "why": "Pure exponent disguise — the size of the power carries zero weight. Reduce mod 3 on sight."
 },
 {
  "id": "b24",
  "trap": "D",
  "difficulty": 2,
  "prompt": "Value of (1 + ω)^4 ?",
  "options": [
   "ω",
   "ω²",
   "1",
   "-ω²",
   "-1",
   "-ω"
  ],
  "answer": 1,
  "script": [
   "1 + ω = −ω².",
   "(−ω²)^4 = (−1)^4·ω^2."
  ],
  "mistake": "Expanding the binomial instead of rewriting 1+ω = −ω².",
  "why": "Sign-bait: rewrite the base first, then the power is a one-liner."
 },
 {
  "id": "b63",
  "trap": "H",
  "difficulty": 3,
  "prompt": "Value of (3 + ω + 2ω²)/(1 + 2ω + 3ω²) ?",
  "options": [
   "1",
   "-1",
   "ω",
   "ω²"
  ],
  "answer": 2,
  "script": [
   "Denominator·ω = numerator ⇒ ratio = ω."
  ],
  "mistake": "Missing the cyclic relationship between the two expressions.",
  "why": "Reverse of the previous — the ratio flips to ω."
 },
 {
  "id": "b48",
  "trap": "G",
  "difficulty": 1,
  "prompt": "The angle (in degrees) between two consecutive 10th roots of unity is:",
  "options": [
   "54",
   "36",
   "72",
   "18"
  ],
  "answer": 1,
  "script": [
   "The n roots are equally spaced around the circle.",
   "Separation = 360°/10 = 36°."
  ],
  "mistake": "Halving or doubling the spacing.",
  "why": "Equal spacing means 2π/10 = 36° between neighbours."
 },
 {
  "id": "b28",
  "trap": "D",
  "difficulty": 3,
  "prompt": "Value of (1 − ω + ω²)³ + (1 + ω − ω²)³ ?",
  "options": [
   "0",
   "-8",
   "16",
   "-16"
  ],
  "answer": 3,
  "script": [
   "Brackets = −2ω and −2ω².",
   "(−2ω)³+(−2ω²)³ = −8−8 = −16."
  ],
  "mistake": "One sign wrong → +16 or 0 (the distractors).",
  "why": "Two sign-baits summed; distractors are exactly the single-error answers."
 },
 {
  "id": "b36",
  "trap": "F",
  "difficulty": 2,
  "prompt": "The determinant |1 ω ω² ; ω ω² 1 ; ω² 1 ω| equals:",
  "options": [
   "1",
   "0",
   "3",
   "-3"
  ],
  "answer": 1,
  "script": [
   "Add all columns into column 1 → each row sums to 1+ω+ω² = 0.",
   "A zero column ⇒ determinant = 0."
  ],
  "mistake": "Cofactor-expanding instead of spotting the zero row-sum.",
  "why": "Cyclic rows of 1,ω,ω² always sum to 0 per row → instant zero."
 },
 {
  "id": "b13",
  "trap": "C",
  "difficulty": 3,
  "prompt": "Remainder when x^100 + x^50 + 1 is divided by x² + x + 1 (give its value at x = ω):",
  "options": [
   "ω",
   "-1",
   "0",
   "1"
  ],
  "answer": 2,
  "script": [
   "Roots of x²+x+1 are ω, ω²; the remainder equals the polynomial at x = ω.",
   "Plug x=ω, reduce powers mod 3 → ω+ω²+1 = 0."
  ],
  "mistake": "Attempting polynomial long division instead of evaluating at the root.",
  "why": "x²+x+1 is a disguise for (x−ω)(x−ω²) — evaluate at ω, never long-divide."
 },
 {
  "id": "b3",
  "trap": "A",
  "difficulty": 1,
  "prompt": "If ω is a non-real cube root of unity, then ω^64 = ?",
  "options": [
   "ω",
   "-1",
   "1",
   "ω²"
  ],
  "answer": 0,
  "script": [
   "64 mod 3 = 1.",
   "ω^64 = ω^1 = ω."
  ],
  "mistake": "Letting the big exponent intimidate you, or reducing mod 2 instead of mod 3.",
  "why": "Pure exponent disguise — the size of the power carries zero weight. Reduce mod 3 on sight."
 },
 {
  "id": "b39",
  "trap": "G",
  "difficulty": 1,
  "prompt": "For a non-zero complex number z, how many distinct values does z^(1/5) have?",
  "options": [
   "5",
   "4",
   "2",
   "1"
  ],
  "answer": 0,
  "script": [
   "Every non-zero z has exactly n distinct nth roots.",
   "Here n = 5."
  ],
  "mistake": "Thinking there is one root, or 2 like a square root.",
  "why": "nth roots come in exactly n, equally spaced 2π/5 apart."
 },
 {
  "id": "b74",
  "trap": "G",
  "difficulty": 2,
  "prompt": "The product of all 5th roots of unity is:",
  "options": [
   "-1",
   "0",
   "5",
   "1"
  ],
  "answer": 3,
  "script": [
   "Product of nth roots of unity = (−1)^(n+1).",
   "For n=5 this is 1."
  ],
  "mistake": "Assuming the product is always 1.",
  "why": "Sign alternates with n: odd n → 1, even n → −1."
 },
 {
  "id": "b20",
  "trap": "C",
  "difficulty": 3,
  "prompt": "For ω a cube root of unity, the value of ω^10 + ω^5 + 1 is:",
  "options": [
   "3",
   "0",
   "1",
   "ω"
  ],
  "answer": 1,
  "script": [
   "Reduce ω^10=ω^1, ω^5=ω^2.",
   "Get ω+ω²+1 = 0."
  ],
  "mistake": "Assuming the answer is always 0 — it is 3 exactly when n is a multiple of 3.",
  "why": "Same shape, different answer by n mod 3. The examiner flips 0↔3 to punish autopilot."
 },
 {
  "id": "b80",
  "trap": "H",
  "difficulty": 2,
  "prompt": "Value of 1³ + 2³ + 4³ − 3·1·2·4 ?",
  "options": [
   "73",
   "52",
   "49",
   "0"
  ],
  "answer": 2,
  "script": [
   "Use a³+b³+c³−3abc = (a+b+c)(a²+b²+c²−ab−bc−ca).",
   "= (7)·(7) = 49."
  ],
  "mistake": "Computing each cube separately and slipping arithmetic.",
  "why": "The ω-factorization (a+bω+cω²)(a+bω²+cω) underlies this identity — recognize and factor."
 },
 {
  "id": "b35",
  "trap": "E",
  "difficulty": 2,
  "prompt": "The distance between the points ω and ω² in the Argand plane is:",
  "options": [
   "√3",
   "1",
   "√2",
   "2"
  ],
  "answer": 0,
  "script": [
   "|ω−ω²| = |i√3| = √3."
  ],
  "mistake": "Thinking adjacent roots are distance 1 apart.",
  "why": "ω and ω² differ by i√3 — a √3 chord."
 },
 {
  "id": "b34",
  "trap": "E",
  "difficulty": 2,
  "prompt": "The perimeter of the triangle with vertices 1, ω, ω² is:",
  "options": [
   "√3",
   "3√3",
   "3",
   "2√3"
  ],
  "answer": 1,
  "script": [
   "Side = |1−ω| = √3 (chord of 120° on unit circle).",
   "Perimeter = 3√3."
  ],
  "mistake": "Using side √2.",
  "why": "Each side is the 120° chord = √3; ×3."
 },
 {
  "id": "b43",
  "trap": "G",
  "difficulty": 2,
  "prompt": "Each of the 4th roots of 16 has modulus:",
  "options": [
   "1",
   "2",
   "4",
   "3"
  ],
  "answer": 1,
  "script": [
   "Modulus of every nth root = |w|^(1/n).",
   "|16|^(1/4) = 2."
  ],
  "mistake": "Taking the modulus of the number itself, not its nth root.",
  "why": "All nth roots lie on one circle of radius |w|^(1/n) = 2."
 },
 {
  "id": "b10",
  "trap": "B",
  "difficulty": 2,
  "prompt": "Value of ω^1 + ω^2 ?",
  "options": [
   "0",
   "1",
   "-1",
   "ω"
  ],
  "answer": 2,
  "script": [
   "Reduce: ω^1=ω^1, ω^2=ω^2.",
   "Their sum is ω+ω² = −1."
  ],
  "mistake": "Computing huge powers directly instead of reducing first.",
  "why": "Two powers chosen so they reduce to ω + ω² = −1."
 },
 {
  "id": "b55",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Which of these is a 4th root of 16?",
  "options": [
   "2i",
   "2+2i",
   "1+i",
   "√3+i"
  ],
  "answer": 0,
  "script": [
   "Convert 16 to polar; its 4 roots have modulus |16|^(1/4) at equally spaced arguments.",
   "Only 2i matches both modulus and an allowed argument: (2i)^4 = 16."
  ],
  "mistake": "Picking a number with the right modulus but the wrong argument.",
  "why": "Polar-first: a true root must match BOTH the modulus and one of the n allowed angles."
 },
 {
  "id": "b67",
  "trap": "H",
  "difficulty": 3,
  "prompt": "For integers a, b, c (not all equal), the minimum value of |a + bω + cω²| is:",
  "options": [
   "√2",
   "1",
   "0",
   "√3"
  ],
  "answer": 1,
  "script": [
   "|a+bω+cω²|² = ½[(a−b)²+(b−c)²+(c−a)²].",
   "Smallest nonzero integer case (e.g. a=1,b=0,c=0) gives 1."
  ],
  "mistake": "Forgetting the cross terms — it is NOT a²+b²+c².",
  "why": "The modulus-squared is a symmetric quadratic; minimizing it over integers gives 1."
 },
 {
  "id": "b47",
  "trap": "G",
  "difficulty": 1,
  "prompt": "The angle (in degrees) between two consecutive 6th roots of unity is:",
  "options": [
   "120",
   "90",
   "30",
   "60"
  ],
  "answer": 3,
  "script": [
   "The n roots are equally spaced around the circle.",
   "Separation = 360°/6 = 60°."
  ],
  "mistake": "Halving or doubling the spacing.",
  "why": "Equal spacing means 2π/6 = 60° between neighbours."
 },
 {
  "id": "b37",
  "trap": "F",
  "difficulty": 2,
  "prompt": "The determinant |1 ω ω² ; ω² 1 ω ; ω ω² 1| equals:",
  "options": [
   "1",
   "3",
   "-1",
   "0"
  ],
  "answer": 3,
  "script": [
   "Every row sums to 1+ω+ω² = 0 ⇒ add columns into one → zero column.",
   "Determinant = 0."
  ],
  "mistake": "Expanding the full 3×3.",
  "why": "Row-sum-zero forces a zero determinant."
 },
 {
  "id": "b26",
  "trap": "D",
  "difficulty": 2,
  "prompt": "Value of (1 − ω + ω²)³ ?",
  "options": [
   "-8",
   "-8ω",
   "8ω²",
   "8"
  ],
  "answer": 0,
  "script": [
   "1+ω²=−ω ⇒ 1−ω+ω² = −2ω.",
   "(−2ω)³ = −8ω³ = −8."
  ],
  "mistake": "Sign slip turning −2ω into +2ω².",
  "why": "Rewrite collapses the bracket to −2ω before cubing."
 },
 {
  "id": "b27",
  "trap": "D",
  "difficulty": 2,
  "prompt": "Value of (1 + ω − ω²)³ ?",
  "options": [
   "8",
   "-8ω²",
   "-8",
   "-16"
  ],
  "answer": 2,
  "script": [
   "1+ω=−ω² ⇒ 1+ω−ω² = −2ω².",
   "(−2ω²)³ = −8ω⁶ = −8."
  ],
  "mistake": "Confusing −2ω² with −2ω.",
  "why": "Mirror of the previous trap; collapses to −2ω²."
 },
 {
  "id": "b21",
  "trap": "C",
  "difficulty": 2,
  "prompt": "Value of ω^3 − 1 ?",
  "options": [
   "1",
   "0",
   "-1",
   "ω"
  ],
  "answer": 1,
  "script": [
   "3 is a multiple of 3 ⇒ ω^3 = 1.",
   "1 − 1 = 0."
  ],
  "mistake": "Forgetting ω^(3k)=1.",
  "why": "Multiples of 3 collapse the power to 1."
 },
 {
  "id": "b49",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Among the cube roots of −8, the smallest positive argument (degrees) is:",
  "options": [
   "0",
   "60",
   "120",
   "150"
  ],
  "answer": 1,
  "script": [
   "Write −8 in polar form r∠θ.",
   "Root arguments are (θ + 360k)/3; the smallest positive is 60°."
  ],
  "mistake": "Forgetting to divide the argument by n, or using θ=0 for a negative number.",
  "why": "Polar-first thinking: the argument of the number must be split into n equal slices."
 },
 {
  "id": "b72",
  "trap": "G",
  "difficulty": 2,
  "prompt": "The product of all 3th roots of unity is:",
  "options": [
   "1",
   "-1",
   "3",
   "0"
  ],
  "answer": 0,
  "script": [
   "Product of nth roots of unity = (−1)^(n+1).",
   "For n=3 this is 1."
  ],
  "mistake": "Assuming the product is always 1.",
  "why": "Sign alternates with n: odd n → 1, even n → −1."
 },
 {
  "id": "b45",
  "trap": "G",
  "difficulty": 1,
  "prompt": "The angle (in degrees) between two consecutive 5th roots of unity is:",
  "options": [
   "108",
   "36",
   "72",
   "144"
  ],
  "answer": 2,
  "script": [
   "The n roots are equally spaced around the circle.",
   "Separation = 360°/5 = 72°."
  ],
  "mistake": "Halving or doubling the spacing.",
  "why": "Equal spacing means 2π/5 = 72° between neighbours."
 },
 {
  "id": "b51",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Among the cube roots of 8i, the smallest positive argument (degrees) is:",
  "options": [
   "0",
   "60",
   "120",
   "30"
  ],
  "answer": 3,
  "script": [
   "Write 8i in polar form r∠θ.",
   "Root arguments are (θ + 360k)/3; the smallest positive is 30°."
  ],
  "mistake": "Forgetting to divide the argument by n, or using θ=0 for a negative number.",
  "why": "Polar-first thinking: the argument of the number must be split into n equal slices."
 },
 {
  "id": "b23",
  "trap": "D",
  "difficulty": 2,
  "prompt": "Value of (1 + ω)^2 ?",
  "options": [
   "-ω",
   "1",
   "-ω²",
   "ω²",
   "ω",
   "-1"
  ],
  "answer": 4,
  "script": [
   "1 + ω = −ω².",
   "(−ω²)^2 = (−1)^2·ω^1."
  ],
  "mistake": "Expanding the binomial instead of rewriting 1+ω = −ω².",
  "why": "Sign-bait: rewrite the base first, then the power is a one-liner."
 },
 {
  "id": "b46",
  "trap": "G",
  "difficulty": 1,
  "prompt": "The angle (in degrees) between two consecutive 8th roots of unity is:",
  "options": [
   "23",
   "90",
   "45",
   "68"
  ],
  "answer": 2,
  "script": [
   "The n roots are equally spaced around the circle.",
   "Separation = 360°/8 = 45°."
  ],
  "mistake": "Halving or doubling the spacing.",
  "why": "Equal spacing means 2π/8 = 45° between neighbours."
 },
 {
  "id": "b50",
  "trap": "G",
  "difficulty": 3,
  "prompt": "Among the 4th roots of −16, the smallest positive argument (degrees) is:",
  "options": [
   "135",
   "90",
   "0",
   "45"
  ],
  "answer": 3,
  "script": [
   "Write −16 in polar form r∠θ.",
   "Root arguments are (θ + 360k)/4; the smallest positive is 45°."
  ],
  "mistake": "Forgetting to divide the argument by n, or using θ=0 for a negative number.",
  "why": "Polar-first thinking: the argument of the number must be split into n equal slices."
 }
];
